### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by steven6282** [thortex/rpi3-webiopi#32]
I was following the installation guide and made it to this step:
./10_make_deb.sh
This errors on my rpi3 with:

native/bridge.c: At top level:
native/bridge.c:1244:31: error: ‘py_set_pullupdn’ undeclared here (not in a function)
  {"setPullUpDn", (PyCFunction)py_set_pullupdn, METH_VARARGS | METH_KEYWORDS, "Setup the GPIO pull/up down control\nchannel   - BCM GPIO number\n\npull_up_down - PUD_OFF, PUD_UP or PUD_DOWN"},
                               ^
native/bridge.c:177:18: warning: ‘py_set_upllupdn’ defined but not used [-Wunused-function]
 static PyObject _py_set_upllupdn(PyObject *self, PyObject *args, PyObject *kwargs)
                  ^
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
dh_auto_build: python setup.py build --force returned exit code 1
debian/rules:7: recipe for target 'build' failed
make: *_\* [build] Error 1
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed

I fixed it by changing the function py_set_upllupdn in bridge.c to py_set_pullupdn, assuming it is just a typo

**Comment by thortex** [comment]
Thank you for your bug reporting and providing the solution.
I fixed the typo.

**Comment by thortex** [comment]
Hi, steven6282.

I've committed modified source code for the issue #32 with c34cf0f.
Can I close this issue?
