### ISSUE TITLE
Wiki: Add PCA9685 	I2C 12-bits 16-channels PWM to SupportedDevices page

### ISSUE THREAD

**Issue by sumghai** [thortex/rpi3-webiopi#39]
Running rpi3-webiopi on a RPi 3 B+, I can confirm that device support for the PCA9685 I2C 12-bits 16-channels PWM breadout is working properly.

Could you please update the [SupportedDevices](https://github.com/thortex/rpi3-webiopi/wiki/SupportedDevices) wiki page to state this information? I believe Erik Ptak (trouch) was the original author of the library.

**Comment by thortex** [comment]
Thank you for your reporting.
I'll update the wiki later.
